### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by cmbankester** [immense/immybox#25]
- [x] Do not store value in data attribute, #23 
- [x] Open / close triggers, #21 
- [ ] "Showing x of y" text, #11 
- [ ] Overridable default jquery options, #10 
- [ ] Replace click to open with open on focus, #9 
- [ ] Mobile friendly, #4 
- [ ] Demo page

**Comment by cmckni3** [comment]
I think we should close this issue and move it to a PR

**Comment by cmbankester** [comment]
@cmckni3 Done. We can close this.

**Comment by cmbankester** [comment]
See: https://github.com/immense/immybox/pull/34
